#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LinkOM.Resource", IsApplication=true)]

namespace LinkOM
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.alliance.calendar.Resource.Animation.cal_fade_in = global::LinkOM.Resource.Animation.cal_fade_in;
			global::com.alliance.calendar.Resource.Animation.cal_slide_down = global::LinkOM.Resource.Animation.cal_slide_down;
			global::com.alliance.calendar.Resource.Animation.cal_slide_up = global::LinkOM.Resource.Animation.cal_slide_up;
			global::com.alliance.calendar.Resource.Attribute.calendar_background = global::LinkOM.Resource.Attribute.calendar_background;
			global::com.alliance.calendar.Resource.Attribute.calendar_cellbackground = global::LinkOM.Resource.Attribute.calendar_cellbackground;
			global::com.alliance.calendar.Resource.Attribute.calendar_highlight_cellbackground = global::LinkOM.Resource.Attribute.calendar_highlight_cellbackground;
			global::com.alliance.calendar.Resource.Attribute.calendar_next_text = global::LinkOM.Resource.Attribute.calendar_next_text;
			global::com.alliance.calendar.Resource.Attribute.calendar_nextbutton_background = global::LinkOM.Resource.Attribute.calendar_nextbutton_background;
			global::com.alliance.calendar.Resource.Attribute.calendar_prev_text = global::LinkOM.Resource.Attribute.calendar_prev_text;
			global::com.alliance.calendar.Resource.Attribute.calendar_prevbutton_background = global::LinkOM.Resource.Attribute.calendar_prevbutton_background;
			global::com.alliance.calendar.Resource.Attribute.calendar_separator = global::LinkOM.Resource.Attribute.calendar_separator;
			global::com.alliance.calendar.Resource.Attribute.calendar_shownextmonthsfromcurrentmonth = global::LinkOM.Resource.Attribute.calendar_shownextmonthsfromcurrentmonth;
			global::com.alliance.calendar.Resource.Attribute.calendar_showonlycurrentmonth = global::LinkOM.Resource.Attribute.calendar_showonlycurrentmonth;
			global::com.alliance.calendar.Resource.Attribute.calendar_showprevmonthsfromcurrentmonth = global::LinkOM.Resource.Attribute.calendar_showprevmonthsfromcurrentmonth;
			global::com.alliance.calendar.Resource.Attribute.calendar_weekstartswith = global::LinkOM.Resource.Attribute.calendar_weekstartswith;
			global::com.alliance.calendar.Resource.Color.black = global::LinkOM.Resource.Color.black;
			global::com.alliance.calendar.Resource.Color.daycell_default_bottom = global::LinkOM.Resource.Color.daycell_default_bottom;
			global::com.alliance.calendar.Resource.Color.daycell_default_middle = global::LinkOM.Resource.Color.daycell_default_middle;
			global::com.alliance.calendar.Resource.Color.daycell_default_top = global::LinkOM.Resource.Color.daycell_default_top;
			global::com.alliance.calendar.Resource.Color.daycell_dim_bottom = global::LinkOM.Resource.Color.daycell_dim_bottom;
			global::com.alliance.calendar.Resource.Color.daycell_dim_middle = global::LinkOM.Resource.Color.daycell_dim_middle;
			global::com.alliance.calendar.Resource.Color.daycell_dim_top = global::LinkOM.Resource.Color.daycell_dim_top;
			global::com.alliance.calendar.Resource.Color.daycell_highlight_bottom = global::LinkOM.Resource.Color.daycell_highlight_bottom;
			global::com.alliance.calendar.Resource.Color.daycell_highlight_middle = global::LinkOM.Resource.Color.daycell_highlight_middle;
			global::com.alliance.calendar.Resource.Color.daycell_highlight_top = global::LinkOM.Resource.Color.daycell_highlight_top;
			global::com.alliance.calendar.Resource.Color.daycell_selected_bottom = global::LinkOM.Resource.Color.daycell_selected_bottom;
			global::com.alliance.calendar.Resource.Color.daycell_selected_middle = global::LinkOM.Resource.Color.daycell_selected_middle;
			global::com.alliance.calendar.Resource.Color.daycell_selected_top = global::LinkOM.Resource.Color.daycell_selected_top;
			global::com.alliance.calendar.Resource.Color.daynamecell_default_bottom = global::LinkOM.Resource.Color.daynamecell_default_bottom;
			global::com.alliance.calendar.Resource.Color.daynamecell_default_middle = global::LinkOM.Resource.Color.daynamecell_default_middle;
			global::com.alliance.calendar.Resource.Color.daynamecell_default_top = global::LinkOM.Resource.Color.daynamecell_default_top;
			global::com.alliance.calendar.Resource.Color.white = global::LinkOM.Resource.Color.white;
			global::com.alliance.calendar.Resource.Drawable.daynamecell_drawable = global::LinkOM.Resource.Drawable.daynamecell_drawable;
			global::com.alliance.calendar.Resource.Drawable.default_cell_selector = global::LinkOM.Resource.Drawable.default_cell_selector;
			global::com.alliance.calendar.Resource.Drawable.default_dim_selector = global::LinkOM.Resource.Drawable.default_dim_selector;
			global::com.alliance.calendar.Resource.Drawable.default_highlight_selector = global::LinkOM.Resource.Drawable.default_highlight_selector;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_Gridview_Days = global::LinkOM.Resource.Id.Alliance_Calendar_Gridview_Days;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_GridviewdayNames = global::LinkOM.Resource.Id.Alliance_Calendar_GridviewdayNames;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_Num_Day = global::LinkOM.Resource.Id.Alliance_Calendar_Num_Day;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_btnNext = global::LinkOM.Resource.Id.Alliance_Calendar_btnNext;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_btnPrev = global::LinkOM.Resource.Id.Alliance_Calendar_btnPrev;
			global::com.alliance.calendar.Resource.Id.Alliance_Calendar_txtYearMonth = global::LinkOM.Resource.Id.Alliance_Calendar_txtYearMonth;
			global::com.alliance.calendar.Resource.Id.monday = global::LinkOM.Resource.Id.monday;
			global::com.alliance.calendar.Resource.Id.sunday = global::LinkOM.Resource.Id.sunday;
			global::com.alliance.calendar.Resource.Layout.Alliance_Calendar_Main = global::LinkOM.Resource.Layout.Alliance_Calendar_Main;
			global::com.alliance.calendar.Resource.Layout.day_gridcell = global::LinkOM.Resource.Layout.day_gridcell;
			global::com.alliance.calendar.Resource.String.ApplicationName = global::LinkOM.Resource.String.ApplicationName;
			global::com.alliance.calendar.Resource.String.Hello = global::LinkOM.Resource.String.Hello;
			global::com.alliance.calendar.Resource.Style.calendar_default_cell_text = global::LinkOM.Resource.Style.calendar_default_cell_text;
			global::com.alliance.calendar.Resource.Style.calendar_default_highlight_text = global::LinkOM.Resource.Style.calendar_default_highlight_text;
			global::com.alliance.calendar.Resource.Style.calendar_default_weekend_text = global::LinkOM.Resource.Style.calendar_default_weekend_text;
			global::com.alliance.calendar.Resource.Styleable.calendarthis = global::LinkOM.Resource.Styleable.calendarthis;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_background = global::LinkOM.Resource.Styleable.calendarthis_calendar_background;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_cellbackground = global::LinkOM.Resource.Styleable.calendarthis_calendar_cellbackground;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_highlight_cellbackground = global::LinkOM.Resource.Styleable.calendarthis_calendar_highlight_cellbackground;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_next_text = global::LinkOM.Resource.Styleable.calendarthis_calendar_next_text;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_nextbutton_background = global::LinkOM.Resource.Styleable.calendarthis_calendar_nextbutton_background;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_prev_text = global::LinkOM.Resource.Styleable.calendarthis_calendar_prev_text;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_prevbutton_background = global::LinkOM.Resource.Styleable.calendarthis_calendar_prevbutton_background;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_separator = global::LinkOM.Resource.Styleable.calendarthis_calendar_separator;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_shownextmonthsfromcurrentmonth = global::LinkOM.Resource.Styleable.calendarthis_calendar_shownextmonthsfromcurrentmonth;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_showonlycurrentmonth = global::LinkOM.Resource.Styleable.calendarthis_calendar_showonlycurrentmonth;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_showprevmonthsfromcurrentmonth = global::LinkOM.Resource.Styleable.calendarthis_calendar_showprevmonthsfromcurrentmonth;
			global::com.alliance.calendar.Resource.Styleable.calendarthis_calendar_weekstartswith = global::LinkOM.Resource.Styleable.calendarthis_calendar_weekstartswith;
			global::MonoDroid.TimesSquare.Resource.Attribute.dayBackground = global::LinkOM.Resource.Attribute.dayBackground;
			global::MonoDroid.TimesSquare.Resource.Attribute.dayTextColor = global::LinkOM.Resource.Attribute.dayTextColor;
			global::MonoDroid.TimesSquare.Resource.Attribute.dividerColor = global::LinkOM.Resource.Attribute.dividerColor;
			global::MonoDroid.TimesSquare.Resource.Attribute.headerTextColor = global::LinkOM.Resource.Attribute.headerTextColor;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_current_month = global::LinkOM.Resource.Attribute.state_current_month;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_highlighted = global::LinkOM.Resource.Attribute.state_highlighted;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_range_first = global::LinkOM.Resource.Attribute.state_range_first;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_range_last = global::LinkOM.Resource.Attribute.state_range_last;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_range_middle = global::LinkOM.Resource.Attribute.state_range_middle;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_selectable = global::LinkOM.Resource.Attribute.state_selectable;
			global::MonoDroid.TimesSquare.Resource.Attribute.state_today = global::LinkOM.Resource.Attribute.state_today;
			global::MonoDroid.TimesSquare.Resource.Attribute.titleTextColor = global::LinkOM.Resource.Attribute.titleTextColor;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_active_month_bg = global::LinkOM.Resource.Color.calendar_active_month_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_bg = global::LinkOM.Resource.Color.calendar_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_divider = global::LinkOM.Resource.Color.calendar_divider;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_highlighted_day_bg = global::LinkOM.Resource.Color.calendar_highlighted_day_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_inactive_month_bg = global::LinkOM.Resource.Color.calendar_inactive_month_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_selected_day_bg = global::LinkOM.Resource.Color.calendar_selected_day_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_selected_range_bg = global::LinkOM.Resource.Color.calendar_selected_range_bg;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_text_active = global::LinkOM.Resource.Color.calendar_text_active;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_text_inactive = global::LinkOM.Resource.Color.calendar_text_inactive;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_text_selected = global::LinkOM.Resource.Color.calendar_text_selected;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_text_selector = global::LinkOM.Resource.Color.calendar_text_selector;
			global::MonoDroid.TimesSquare.Resource.Color.calendar_text_unselectable = global::LinkOM.Resource.Color.calendar_text_unselectable;
			global::MonoDroid.TimesSquare.Resource.Dimension.calendar_day_headers_paddingbottom = global::LinkOM.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::MonoDroid.TimesSquare.Resource.Dimension.calendar_month_title_bottommargin = global::LinkOM.Resource.Dimension.calendar_month_title_bottommargin;
			global::MonoDroid.TimesSquare.Resource.Dimension.calendar_month_topmargin = global::LinkOM.Resource.Dimension.calendar_month_topmargin;
			global::MonoDroid.TimesSquare.Resource.Dimension.calendar_text_medium = global::LinkOM.Resource.Dimension.calendar_text_medium;
			global::MonoDroid.TimesSquare.Resource.Dimension.calendar_text_small = global::LinkOM.Resource.Dimension.calendar_text_small;
			global::MonoDroid.TimesSquare.Resource.Drawable.calendar_bg_selector = global::LinkOM.Resource.Drawable.calendar_bg_selector;
			global::MonoDroid.TimesSquare.Resource.Id.calendar_grid = global::LinkOM.Resource.Id.calendar_grid;
			global::MonoDroid.TimesSquare.Resource.Id.title = global::LinkOM.Resource.Id.title;
			global::MonoDroid.TimesSquare.Resource.Layout.month = global::LinkOM.Resource.Layout.month;
			global::MonoDroid.TimesSquare.Resource.Layout.week = global::LinkOM.Resource.Layout.week;
			global::MonoDroid.TimesSquare.Resource.String.day_name_format = global::LinkOM.Resource.String.day_name_format;
			global::MonoDroid.TimesSquare.Resource.String.full_date_format = global::LinkOM.Resource.String.full_date_format;
			global::MonoDroid.TimesSquare.Resource.String.invalid_date = global::LinkOM.Resource.String.invalid_date;
			global::MonoDroid.TimesSquare.Resource.String.library_name = global::LinkOM.Resource.String.library_name;
			global::MonoDroid.TimesSquare.Resource.String.month_name_format = global::LinkOM.Resource.String.month_name_format;
			global::MonoDroid.TimesSquare.Resource.Style.CalendarCell = global::LinkOM.Resource.Style.CalendarCell;
			global::MonoDroid.TimesSquare.Resource.Style.CalendarCell_CalendarDate = global::LinkOM.Resource.Style.CalendarCell_CalendarDate;
			global::MonoDroid.TimesSquare.Resource.Style.CalendarCell_DayHeader = global::LinkOM.Resource.Style.CalendarCell_DayHeader;
			global::MonoDroid.TimesSquare.Resource.Style.CalendarTitle = global::LinkOM.Resource.Style.CalendarTitle;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView = global::LinkOM.Resource.Styleable.CalendarPickerView;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_android_background = global::LinkOM.Resource.Styleable.CalendarPickerView_android_background;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_dayBackground = global::LinkOM.Resource.Styleable.CalendarPickerView_dayBackground;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_dayTextColor = global::LinkOM.Resource.Styleable.CalendarPickerView_dayTextColor;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_dividerColor = global::LinkOM.Resource.Styleable.CalendarPickerView_dividerColor;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_headerTextColor = global::LinkOM.Resource.Styleable.CalendarPickerView_headerTextColor;
			global::MonoDroid.TimesSquare.Resource.Styleable.CalendarPickerView_titleTextColor = global::LinkOM.Resource.Styleable.CalendarPickerView_titleTextColor;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell = global::LinkOM.Resource.Styleable.calendar_cell;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_current_month = global::LinkOM.Resource.Styleable.calendar_cell_state_current_month;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_highlighted = global::LinkOM.Resource.Styleable.calendar_cell_state_highlighted;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_range_first = global::LinkOM.Resource.Styleable.calendar_cell_state_range_first;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_range_last = global::LinkOM.Resource.Styleable.calendar_cell_state_range_last;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_range_middle = global::LinkOM.Resource.Styleable.calendar_cell_state_range_middle;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_selectable = global::LinkOM.Resource.Styleable.calendar_cell_state_selectable;
			global::MonoDroid.TimesSquare.Resource.Styleable.calendar_cell_state_today = global::LinkOM.Resource.Styleable.calendar_cell_state_today;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int cal_fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cal_slide_down = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cal_slide_up = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0002
			public const int TaskPriority = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int TaskStatus = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int menu = 2131361792;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000d
			public const int calendar_background = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int calendar_cellbackground = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int calendar_highlight_cellbackground = 2130771983;
			
			// aapt resource value: 0x7f010012
			public const int calendar_next_text = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int calendar_nextbutton_background = 2130771985;
			
			// aapt resource value: 0x7f010013
			public const int calendar_prev_text = 2130771987;
			
			// aapt resource value: 0x7f010010
			public const int calendar_prevbutton_background = 2130771984;
			
			// aapt resource value: 0x7f01000c
			public const int calendar_separator = 2130771980;
			
			// aapt resource value: 0x7f010017
			public const int calendar_shownextmonthsfromcurrentmonth = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int calendar_showonlycurrentmonth = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int calendar_showprevmonthsfromcurrentmonth = 2130771990;
			
			// aapt resource value: 0x7f010014
			public const int calendar_weekstartswith = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int dayBackground = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int dayTextColor = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int dividerColor = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int headerTextColor = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int state_current_month = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public const int state_highlighted = 2130771979;
			
			// aapt resource value: 0x7f010008
			public const int state_range_first = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int state_range_last = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int state_range_middle = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int state_selectable = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int state_today = 2130771975;
			
			// aapt resource value: 0x7f010003
			public const int titleTextColor = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060024
			public const int ab_background = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int ab_bottom_shadow_1 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int ab_bottom_shadow_2 = 2131099686;
			
			// aapt resource value: 0x7f060023
			public const int action_bar_title_color = 2131099683;
			
			// aapt resource value: 0x7f06000c
			public const int black = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int calendar_active_month_bg = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int calendar_bg = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int calendar_divider = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int calendar_highlighted_day_bg = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int calendar_inactive_month_bg = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_selected_day_bg = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int calendar_selected_range_bg = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int calendar_text_active = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int calendar_text_inactive = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int calendar_text_selected = 2131099657;
			
			// aapt resource value: 0x7f060027
			public const int calendar_text_selector = 2131099687;
			
			// aapt resource value: 0x7f06000a
			public const int calendar_text_unselectable = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int daycell_default_bottom = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int daycell_default_middle = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int daycell_default_top = 2131099661;
			
			// aapt resource value: 0x7f060015
			public const int daycell_dim_bottom = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int daycell_dim_middle = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int daycell_dim_top = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int daycell_highlight_bottom = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int daycell_highlight_middle = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int daycell_highlight_top = 2131099664;
			
			// aapt resource value: 0x7f060018
			public const int daycell_selected_bottom = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int daycell_selected_middle = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int daycell_selected_top = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int daynamecell_default_bottom = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int daynamecell_default_middle = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int daynamecell_default_top = 2131099673;
			
			// aapt resource value: 0x7f060022
			public const int main_background = 2131099682;
			
			// aapt resource value: 0x7f06000b
			public const int white = 2131099659;
			
			// aapt resource value: 0x7f06001d
			public const int xam_blue = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int xam_dark_blue = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int xam_gray = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int xam_green = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int xam_light_gray = 2131099681;
			
			// aapt resource value: 0x7f06001c
			public const int xam_purple = 2131099676;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int calendar_day_headers_paddingbottom = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int calendar_month_title_bottommargin = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int calendar_month_topmargin = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int calendar_text_medium = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int calendar_text_small = 2131165188;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Add_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Add_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Add_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Back_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Back_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Back_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Background2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Background3 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int calendar_bg_selector = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int close = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int daynamecell_drawable = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int default_cell_selector = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int default_dim_selector = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int default_highlight_selector = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Document_button = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Document_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Document_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Documents = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int edit_text_style = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Help = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int icon1 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int iconelse = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Issues = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Issues_button = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Issues_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Issues_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Linkom = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int LinkOM_Logo = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Lock_button = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Lock_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Lock_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Milestone_button = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Milestone_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Milestone_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Milestones = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int open = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Profile = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Project_button = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Project_normal = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Project_pressed = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Projects = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int RoundButton = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Search_button = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Search_normal = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Search_pressed = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Server = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int star_logo = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Synotive = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int Synotive_White = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Synquis_Logo = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int Task_button = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int Task_normal = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Task_pressed = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Tasks = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Ticket_button = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Ticket_normal = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Ticket_pressed = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int Tickets = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int widget_bg = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int widget_bg_normal = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int widget_bg_pressed = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int widget_bg_selected = 2130837568;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0015
			public const int AddButton = 2131492885;
			
			// aapt resource value: 0x7f0c0006
			public const int Alliance_Calendar_Gridview_Days = 2131492870;
			
			// aapt resource value: 0x7f0c0005
			public const int Alliance_Calendar_GridviewdayNames = 2131492869;
			
			// aapt resource value: 0x7f0c000f
			public const int Alliance_Calendar_Num_Day = 2131492879;
			
			// aapt resource value: 0x7f0c0004
			public const int Alliance_Calendar_btnNext = 2131492868;
			
			// aapt resource value: 0x7f0c0002
			public const int Alliance_Calendar_btnPrev = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int Alliance_Calendar_txtYearMonth = 2131492867;
			
			// aapt resource value: 0x7f0c0013
			public const int BackButton = 2131492883;
			
			// aapt resource value: 0x7f0c000d
			public const int CheckButton = 2131492877;
			
			// aapt resource value: 0x7f0c0010
			public const int FlyOutContent = 2131492880;
			
			// aapt resource value: 0x7f0c003c
			public const int FlyOutMenu = 2131492924;
			
			// aapt resource value: 0x7f0c0024
			public const int IssuesListView = 2131492900;
			
			// aapt resource value: 0x7f0c002b
			public const int MainContainer = 2131492907;
			
			// aapt resource value: 0x7f0c003a
			public const int MenuButton = 2131492922;
			
			// aapt resource value: 0x7f0c0023
			public const int SearchButton = 2131492899;
			
			// aapt resource value: 0x7f0c003b
			public const int SignOutButton = 2131492923;
			
			// aapt resource value: 0x7f0c0053
			public const int TaskListView = 2131492947;
			
			// aapt resource value: 0x7f0c00b6
			public const int TicketListView = 2131493046;
			
			// aapt resource value: 0x7f0c000b
			public const int URLText = 2131492875;
			
			// aapt resource value: 0x7f0c00ba
			public const int blog_title = 2131493050;
			
			// aapt resource value: 0x7f0c002a
			public const int btLogin = 2131492906;
			
			// aapt resource value: 0x7f0c0050
			public const int bt_Back = 2131492944;
			
			// aapt resource value: 0x7f0c0034
			public const int bt_Document = 2131492916;
			
			// aapt resource value: 0x7f0c009b
			public const int bt_EndDate = 2131493019;
			
			// aapt resource value: 0x7f0c0033
			public const int bt_Issues = 2131492915;
			
			// aapt resource value: 0x7f0c0031
			public const int bt_Milestone = 2131492913;
			
			// aapt resource value: 0x7f0c002e
			public const int bt_Project = 2131492910;
			
			// aapt resource value: 0x7f0c00a9
			public const int bt_Save = 2131493033;
			
			// aapt resource value: 0x7f0c0099
			public const int bt_StartDate = 2131493017;
			
			// aapt resource value: 0x7f0c002f
			public const int bt_Task = 2131492911;
			
			// aapt resource value: 0x7f0c0030
			public const int bt_Ticket = 2131492912;
			
			// aapt resource value: 0x7f0c00a5
			public const int bt_camera = 2131493029;
			
			// aapt resource value: 0x7f0c00bb
			public const int bullet = 2131493051;
			
			// aapt resource value: 0x7f0c004f
			public const int calendar_grid = 2131492943;
			
			// aapt resource value: 0x7f0c004d
			public const int calendar_view = 2131492941;
			
			// aapt resource value: 0x7f0c00ad
			public const int cancel_button = 2131493037;
			
			// aapt resource value: 0x7f0c001e
			public const int cb_Internal = 2131492894;
			
			// aapt resource value: 0x7f0c00ab
			public const int cb_Management = 2131493035;
			
			// aapt resource value: 0x7f0c00aa
			public const int cb_WatchList = 2131493034;
			
			// aapt resource value: 0x7f0c0029
			public const int cb_rememberMe = 2131492905;
			
			// aapt resource value: 0x7f0c00a0
			public const int checkBox1 = 2131493024;
			
			// aapt resource value: 0x7f0c00a1
			public const int checkBox2 = 2131493025;
			
			// aapt resource value: 0x7f0c00a2
			public const int checkBox3 = 2131493026;
			
			// aapt resource value: 0x7f0c00bc
			public const int creator = 2131493052;
			
			// aapt resource value: 0x7f0c009e
			public const int editText2 = 2131493022;
			
			// aapt resource value: 0x7f0c00ac
			public const int editText_AlloHours = 2131493036;
			
			// aapt resource value: 0x7f0c008c
			public const int editText_Title = 2131493004;
			
			// aapt resource value: 0x7f0c0025
			public const int etSearch = 2131492901;
			
			// aapt resource value: 0x7f0c0088
			public const int field1 = 2131493000;
			
			// aapt resource value: 0x7f0c0089
			public const int field2 = 2131493001;
			
			// aapt resource value: 0x7f0c0012
			public const int frameLayout1 = 2131492882;
			
			// aapt resource value: 0x7f0c000c
			public const int getSection = 2131492876;
			
			// aapt resource value: 0x7f0c00b9
			public const int icon = 2131493049;
			
			// aapt resource value: 0x7f0c0056
			public const int imageStatus = 2131492950;
			
			// aapt resource value: 0x7f0c0008
			public const int imageView1 = 2131492872;
			
			// aapt resource value: 0x7f0c000e
			public const int imageView2 = 2131492878;
			
			// aapt resource value: 0x7f0c0048
			public const int image_Status = 2131492936;
			
			// aapt resource value: 0x7f0c00a6
			public const int iv_Photo = 2131493030;
			
			// aapt resource value: 0x7f0c000a
			public const int latLabel = 2131492874;
			
			// aapt resource value: 0x7f0c0009
			public const int latSection = 2131492873;
			
			// aapt resource value: 0x7f0c0007
			public const int linearLayout1 = 2131492871;
			
			// aapt resource value: 0x7f0c009f
			public const int linearLayout10 = 2131493023;
			
			// aapt resource value: 0x7f0c00a3
			public const int linearLayout11 = 2131493027;
			
			// aapt resource value: 0x7f0c00a8
			public const int linearLayout12 = 2131493032;
			
			// aapt resource value: 0x7f0c0036
			public const int linearLayout2 = 2131492918;
			
			// aapt resource value: 0x7f0c008a
			public const int linearLayout3 = 2131493002;
			
			// aapt resource value: 0x7f0c008d
			public const int linearLayout4 = 2131493005;
			
			// aapt resource value: 0x7f0c008f
			public const int linearLayout5 = 2131493007;
			
			// aapt resource value: 0x7f0c0093
			public const int linearLayout6 = 2131493011;
			
			// aapt resource value: 0x7f0c0095
			public const int linearLayout7 = 2131493013;
			
			// aapt resource value: 0x7f0c0097
			public const int linearLayout8 = 2131493015;
			
			// aapt resource value: 0x7f0c009c
			public const int linearLayout9 = 2131493020;
			
			// aapt resource value: 0x7f0c0022
			public const int linearLayout_Main = 2131492898;
			
			// aapt resource value: 0x7f0c0079
			public const int list_Milestone = 2131492985;
			
			// aapt resource value: 0x7f0c0027
			public const int longSection = 2131492903;
			
			// aapt resource value: 0x7f0c0046
			public const int menu_ChangeServer = 2131492934;
			
			// aapt resource value: 0x7f0c0045
			public const int menu_Document = 2131492933;
			
			// aapt resource value: 0x7f0c0043
			public const int menu_Issues = 2131492931;
			
			// aapt resource value: 0x7f0c0044
			public const int menu_Milestone = 2131492932;
			
			// aapt resource value: 0x7f0c003e
			public const int menu_Project = 2131492926;
			
			// aapt resource value: 0x7f0c003f
			public const int menu_Task = 2131492927;
			
			// aapt resource value: 0x7f0c0042
			public const int menu_Ticket = 2131492930;
			
			// aapt resource value: 0x7f0c00be
			public const int menu_help = 2131493054;
			
			// aapt resource value: 0x7f0c00c0
			public const int menu_reset = 2131493056;
			
			// aapt resource value: 0x7f0c00bd
			public const int menu_search = 2131493053;
			
			// aapt resource value: 0x7f0c00bf
			public const int menu_server = 2131493055;
			
			// aapt resource value: 0x7f0c00b8
			public const int message = 2131493048;
			
			// aapt resource value: 0x7f0c0000
			public const int monday = 2131492864;
			
			// aapt resource value: 0x7f0c00ae
			public const int ok_button = 2131493038;
			
			// aapt resource value: 0x7f0c0017
			public const int refresher = 2131492887;
			
			// aapt resource value: 0x7f0c002c
			public const int relativeLayout1 = 2131492908;
			
			// aapt resource value: 0x7f0c0035
			public const int relativeLayout2 = 2131492917;
			
			// aapt resource value: 0x7f0c0039
			public const int relativeLayout3 = 2131492921;
			
			// aapt resource value: 0x7f0c0055
			public const int scrollView1 = 2131492949;
			
			// aapt resource value: 0x7f0c0094
			public const int sp_AssignedTo = 2131493012;
			
			// aapt resource value: 0x7f0c0096
			public const int sp_Owner = 2131493014;
			
			// aapt resource value: 0x7f0c0092
			public const int sp_Priority = 2131493010;
			
			// aapt resource value: 0x7f0c008e
			public const int sp_Project = 2131493006;
			
			// aapt resource value: 0x7f0c0090
			public const int sp_Status = 2131493008;
			
			// aapt resource value: 0x7f0c0001
			public const int sunday = 2131492865;
			
			// aapt resource value: 0x7f0c0038
			public const int tabcontent = 2131492920;
			
			// aapt resource value: 0x7f0c002d
			public const int tableLayout1 = 2131492909;
			
			// aapt resource value: 0x7f0c0049
			public const int tableLayout2 = 2131492937;
			
			// aapt resource value: 0x7f0c0065
			public const int tableLayout3 = 2131492965;
			
			// aapt resource value: 0x7f0c006c
			public const int tableLayout4 = 2131492972;
			
			// aapt resource value: 0x7f0c0075
			public const int tableLayout5 = 2131492981;
			
			// aapt resource value: 0x7f0c0018
			public const int tableRow1 = 2131492888;
			
			// aapt resource value: 0x7f0c0071
			public const int tableRow10 = 2131492977;
			
			// aapt resource value: 0x7f0c0076
			public const int tableRow11 = 2131492982;
			
			// aapt resource value: 0x7f0c0077
			public const int tableRow12 = 2131492983;
			
			// aapt resource value: 0x7f0c00a7
			public const int tableRow13 = 2131493031;
			
			// aapt resource value: 0x7f0c001a
			public const int tableRow2 = 2131492890;
			
			// aapt resource value: 0x7f0c0032
			public const int tableRow3 = 2131492914;
			
			// aapt resource value: 0x7f0c005d
			public const int tableRow4 = 2131492957;
			
			// aapt resource value: 0x7f0c005e
			public const int tableRow5 = 2131492958;
			
			// aapt resource value: 0x7f0c0062
			public const int tableRow6 = 2131492962;
			
			// aapt resource value: 0x7f0c0066
			public const int tableRow7 = 2131492966;
			
			// aapt resource value: 0x7f0c004a
			public const int tableRow8 = 2131492938;
			
			// aapt resource value: 0x7f0c006d
			public const int tableRow9 = 2131492973;
			
			// aapt resource value: 0x7f0c0037
			public const int tabs = 2131492919;
			
			// aapt resource value: 0x7f0c0087
			public const int text = 2131492999;
			
			// aapt resource value: 0x7f0c003d
			public const int textView1 = 2131492925;
			
			// aapt resource value: 0x7f0c0051
			public const int textView10 = 2131492945;
			
			// aapt resource value: 0x7f0c008b
			public const int textView11 = 2131493003;
			
			// aapt resource value: 0x7f0c0057
			public const int textView12 = 2131492951;
			
			// aapt resource value: 0x7f0c0058
			public const int textView13 = 2131492952;
			
			// aapt resource value: 0x7f0c0091
			public const int textView14 = 2131493009;
			
			// aapt resource value: 0x7f0c0059
			public const int textView15 = 2131492953;
			
			// aapt resource value: 0x7f0c0098
			public const int textView16 = 2131493016;
			
			// aapt resource value: 0x7f0c009a
			public const int textView17 = 2131493018;
			
			// aapt resource value: 0x7f0c009d
			public const int textView18 = 2131493021;
			
			// aapt resource value: 0x7f0c00a4
			public const int textView19 = 2131493028;
			
			// aapt resource value: 0x7f0c0014
			public const int textView2 = 2131492884;
			
			// aapt resource value: 0x7f0c007d
			public const int textView21 = 2131492989;
			
			// aapt resource value: 0x7f0c005f
			public const int textView23 = 2131492959;
			
			// aapt resource value: 0x7f0c0060
			public const int textView24 = 2131492960;
			
			// aapt resource value: 0x7f0c0061
			public const int textView25 = 2131492961;
			
			// aapt resource value: 0x7f0c0067
			public const int textView26 = 2131492967;
			
			// aapt resource value: 0x7f0c0068
			public const int textView27 = 2131492968;
			
			// aapt resource value: 0x7f0c006e
			public const int textView28 = 2131492974;
			
			// aapt resource value: 0x7f0c006f
			public const int textView29 = 2131492975;
			
			// aapt resource value: 0x7f0c0040
			public const int textView3 = 2131492928;
			
			// aapt resource value: 0x7f0c0070
			public const int textView30 = 2131492976;
			
			// aapt resource value: 0x7f0c0081
			public const int textView40 = 2131492993;
			
			// aapt resource value: 0x7f0c0082
			public const int textView41 = 2131492994;
			
			// aapt resource value: 0x7f0c0083
			public const int textView42 = 2131492995;
			
			// aapt resource value: 0x7f0c0084
			public const int textView43 = 2131492996;
			
			// aapt resource value: 0x7f0c00b2
			public const int textView44 = 2131493042;
			
			// aapt resource value: 0x7f0c00b0
			public const int textView46 = 2131493040;
			
			// aapt resource value: 0x7f0c00b3
			public const int textView48 = 2131493043;
			
			// aapt resource value: 0x7f0c0021
			public const int tinyProgress = 2131492897;
			
			// aapt resource value: 0x7f0c004e
			public const int title = 2131492942;
			
			// aapt resource value: 0x7f0c006b
			public const int tv_ActualEndDate = 2131492971;
			
			// aapt resource value: 0x7f0c0085
			public const int tv_ActualHours = 2131492997;
			
			// aapt resource value: 0x7f0c006a
			public const int tv_ActualStartDate = 2131492970;
			
			// aapt resource value: 0x7f0c005c
			public const int tv_AlloHours = 2131492956;
			
			// aapt resource value: 0x7f0c0086
			public const int tv_AllocatedHours = 2131492998;
			
			// aapt resource value: 0x7f0c00b4
			public const int tv_AssignTo = 2131493044;
			
			// aapt resource value: 0x7f0c0069
			public const int tv_Client = 2131492969;
			
			// aapt resource value: 0x7f0c007b
			public const int tv_ClientName = 2131492987;
			
			// aapt resource value: 0x7f0c005a
			public const int tv_Code = 2131492954;
			
			// aapt resource value: 0x7f0c004c
			public const int tv_CreatedPerson = 2131492940;
			
			// aapt resource value: 0x7f0c0072
			public const int tv_DeliveryManager = 2131492978;
			
			// aapt resource value: 0x7f0c0063
			public const int tv_Department = 2131492963;
			
			// aapt resource value: 0x7f0c0080
			public const int tv_DepartmentName = 2131492992;
			
			// aapt resource value: 0x7f0c0020
			public const int tv_Description = 2131492896;
			
			// aapt resource value: 0x7f0c0019
			public const int tv_DocumentName = 2131492889;
			
			// aapt resource value: 0x7f0c0064
			public const int tv_EndDate = 2131492964;
			
			// aapt resource value: 0x7f0c0047
			public const int tv_MilestoneName = 2131492935;
			
			// aapt resource value: 0x7f0c0078
			public const int tv_Notes = 2131492984;
			
			// aapt resource value: 0x7f0c007f
			public const int tv_OpenIssues = 2131492991;
			
			// aapt resource value: 0x7f0c007e
			public const int tv_OpenTasks = 2131492990;
			
			// aapt resource value: 0x7f0c007c
			public const int tv_OpenTickets = 2131492988;
			
			// aapt resource value: 0x7f0c00b5
			public const int tv_Owner = 2131493045;
			
			// aapt resource value: 0x7f0c0074
			public const int tv_ProjectCoordinator = 2131492980;
			
			// aapt resource value: 0x7f0c0073
			public const int tv_ProjectManager = 2131492979;
			
			// aapt resource value: 0x7f0c007a
			public const int tv_ProjectName = 2131492986;
			
			// aapt resource value: 0x7f0c001f
			public const int tv_Publish = 2131492895;
			
			// aapt resource value: 0x7f0c005b
			public const int tv_RefCode = 2131492955;
			
			// aapt resource value: 0x7f0c004b
			public const int tv_StartDate = 2131492939;
			
			// aapt resource value: 0x7f0c00b1
			public const int tv_Status = 2131493041;
			
			// aapt resource value: 0x7f0c00af
			public const int tv_TaskName = 2131493039;
			
			// aapt resource value: 0x7f0c001d
			public const int tv_category = 2131492893;
			
			// aapt resource value: 0x7f0c001c
			public const int tv_label = 2131492892;
			
			// aapt resource value: 0x7f0c0028
			public const int tv_password = 2131492904;
			
			// aapt resource value: 0x7f0c001b
			public const int tv_project = 2131492891;
			
			// aapt resource value: 0x7f0c0054
			public const int tv_projectname = 2131492948;
			
			// aapt resource value: 0x7f0c0026
			public const int tv_username = 2131492902;
			
			// aapt resource value: 0x7f0c0011
			public const int view1 = 2131492881;
			
			// aapt resource value: 0x7f0c0016
			public const int view2 = 2131492886;
			
			// aapt resource value: 0x7f0c0041
			public const int view3 = 2131492929;
			
			// aapt resource value: 0x7f0c0052
			public const int webView1 = 2131492946;
			
			// aapt resource value: 0x7f0c00b7
			public const int widget = 2131493047;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Alliance_Calendar_Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CheckInstance = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int day_gridcell = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Document = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DocumentList = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Issues = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int IssuesListContainer = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Login = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MainContentLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int MenuLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MilestoneList = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Milestones = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int month = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int OpenTaskView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Project = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ProjectDetailLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ProjectList = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int SpinnerItemDropdown = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SpinnerItemText = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int StatusRow = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Task = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int TaskAdd = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int TaskEdit = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int TaskList = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int TaskListContainer = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Ticket = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int TicketListContainer = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int week = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int widget_message = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int widget_word = 2130903070;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int menu_home = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int menu_login = 2131427329;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080006
			public const int ApplicationName = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int Hello = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int day_name_format = 2131230721;
			
			// aapt resource value: 0x7f08000b
			public const int dismissed_message = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int full_date_format = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int invalid_date = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int library_name = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int month_name_format = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int showcase_project_message = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int showcase_project_title = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int showcase_task_message = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int showcase_task_title = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int widget_name = 2131230732;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090009
			public const int BulletPoint = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int CalendarCell = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int CalendarCell_CalendarDate = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int CalendarCell_DayHeader = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int CalendarTitle = 2131296256;
			
			// aapt resource value: 0x7f09000a
			public const int Text = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int Text_BlogTitle = 2131296268;
			
			// aapt resource value: 0x7f09000e
			public const int Text_Creator = 2131296270;
			
			// aapt resource value: 0x7f09000b
			public const int Text_Loading = 2131296267;
			
			// aapt resource value: 0x7f09000d
			public const int Text_WordType = 2131296269;
			
			// aapt resource value: 0x7f090007
			public const int Theme_Splash = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int WidgetBackground = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int calendar_default_cell_text = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int calendar_default_highlight_text = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int calendar_default_weekend_text = 2131296262;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int widget_word = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CalendarPickerView = new int[] {
					16842964,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 0
			public const int CalendarPickerView_android_background = 0;
			
			// aapt resource value: 2
			public const int CalendarPickerView_dayBackground = 2;
			
			// aapt resource value: 3
			public const int CalendarPickerView_dayTextColor = 3;
			
			// aapt resource value: 1
			public const int CalendarPickerView_dividerColor = 1;
			
			// aapt resource value: 5
			public const int CalendarPickerView_headerTextColor = 5;
			
			// aapt resource value: 4
			public const int CalendarPickerView_titleTextColor = 4;
			
			public static int[] calendar_cell = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int calendar_cell_state_current_month = 1;
			
			// aapt resource value: 6
			public const int calendar_cell_state_highlighted = 6;
			
			// aapt resource value: 3
			public const int calendar_cell_state_range_first = 3;
			
			// aapt resource value: 5
			public const int calendar_cell_state_range_last = 5;
			
			// aapt resource value: 4
			public const int calendar_cell_state_range_middle = 4;
			
			// aapt resource value: 0
			public const int calendar_cell_state_selectable = 0;
			
			// aapt resource value: 2
			public const int calendar_cell_state_today = 2;
			
			public static int[] calendarthis = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 1
			public const int calendarthis_calendar_background = 1;
			
			// aapt resource value: 2
			public const int calendarthis_calendar_cellbackground = 2;
			
			// aapt resource value: 3
			public const int calendarthis_calendar_highlight_cellbackground = 3;
			
			// aapt resource value: 6
			public const int calendarthis_calendar_next_text = 6;
			
			// aapt resource value: 5
			public const int calendarthis_calendar_nextbutton_background = 5;
			
			// aapt resource value: 7
			public const int calendarthis_calendar_prev_text = 7;
			
			// aapt resource value: 4
			public const int calendarthis_calendar_prevbutton_background = 4;
			
			// aapt resource value: 0
			public const int calendarthis_calendar_separator = 0;
			
			// aapt resource value: 11
			public const int calendarthis_calendar_shownextmonthsfromcurrentmonth = 11;
			
			// aapt resource value: 9
			public const int calendarthis_calendar_showonlycurrentmonth = 9;
			
			// aapt resource value: 10
			public const int calendarthis_calendar_showprevmonthsfromcurrentmonth = 10;
			
			// aapt resource value: 8
			public const int calendarthis_calendar_weekstartswith = 8;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
