#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LinkOM.Resource", IsApplication=true)]

namespace LinkOM
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040002
			public const int TaskPriority = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int TaskStatus = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int menu = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Add_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Add_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Add_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Back_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Back_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Back_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Background2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int close = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Document_button = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Document_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Document_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Documents = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Help = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int iconelse = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Issues = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Issues_button = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Issues_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Issues_pressed = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Linkom = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int LinkOM_Logo = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Lock_button = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Lock_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Lock_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Milestone_button = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Milestone_normal = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Milestone_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Milestones = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int open = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Project_button = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Project_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Project_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Projects = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int RoundButton = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Search_button = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Search_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Search_pressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Synotive = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Synotive_White = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Synquis_Logo = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Task_button = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Task_normal = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Task_pressed = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Tasks = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Ticket_button = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Ticket_normal = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Ticket_pressed = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Tickets = 2130837554;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070067
			public const int AddButton = 2131165287;
			
			// aapt resource value: 0x7f070004
			public const int BackButton = 2131165188;
			
			// aapt resource value: 0x7f07003d
			public const int CheckButton = 2131165245;
			
			// aapt resource value: 0x7f070000
			public const int FlyOutContent = 2131165184;
			
			// aapt resource value: 0x7f070054
			public const int FlyOutMenu = 2131165268;
			
			// aapt resource value: 0x7f070051
			public const int MainContainer = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int MenuButton = 2131165266;
			
			// aapt resource value: 0x7f070053
			public const int SignOutButton = 2131165267;
			
			// aapt resource value: 0x7f070066
			public const int TaskListView = 2131165286;
			
			// aapt resource value: 0x7f07003b
			public const int URLText = 2131165243;
			
			// aapt resource value: 0x7f07004f
			public const int btLogin = 2131165263;
			
			// aapt resource value: 0x7f070063
			public const int bt_Back = 2131165283;
			
			// aapt resource value: 0x7f070095
			public const int bt_Close = 2131165333;
			
			// aapt resource value: 0x7f070046
			public const int bt_Document = 2131165254;
			
			// aapt resource value: 0x7f070024
			public const int bt_EndDate = 2131165220;
			
			// aapt resource value: 0x7f070045
			public const int bt_Issues = 2131165253;
			
			// aapt resource value: 0x7f070044
			public const int bt_Milestone = 2131165252;
			
			// aapt resource value: 0x7f070094
			public const int bt_Open = 2131165332;
			
			// aapt resource value: 0x7f070097
			public const int bt_Progress = 2131165335;
			
			// aapt resource value: 0x7f070041
			public const int bt_Project = 2131165249;
			
			// aapt resource value: 0x7f070098
			public const int bt_Query = 2131165336;
			
			// aapt resource value: 0x7f070037
			public const int bt_Save = 2131165239;
			
			// aapt resource value: 0x7f070021
			public const int bt_StartDate = 2131165217;
			
			// aapt resource value: 0x7f070042
			public const int bt_Task = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int bt_Ticket = 2131165251;
			
			// aapt resource value: 0x7f070096
			public const int bt_Waiting = 2131165334;
			
			// aapt resource value: 0x7f070033
			public const int bt_camera = 2131165235;
			
			// aapt resource value: 0x7f07004e
			public const int cb_rememberMe = 2131165262;
			
			// aapt resource value: 0x7f07002d
			public const int checkBox1 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int checkBox2 = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int checkBox3 = 2131165231;
			
			// aapt resource value: 0x7f07002a
			public const int editText2 = 2131165226;
			
			// aapt resource value: 0x7f07000b
			public const int editText_Title = 2131165195;
			
			// aapt resource value: 0x7f070092
			public const int field1 = 2131165330;
			
			// aapt resource value: 0x7f070093
			public const int field2 = 2131165331;
			
			// aapt resource value: 0x7f070002
			public const int frameLayout1 = 2131165186;
			
			// aapt resource value: 0x7f07003c
			public const int getSection = 2131165244;
			
			// aapt resource value: 0x7f07006a
			public const int imageStatus = 2131165290;
			
			// aapt resource value: 0x7f070038
			public const int imageView1 = 2131165240;
			
			// aapt resource value: 0x7f07003e
			public const int imageView2 = 2131165246;
			
			// aapt resource value: 0x7f070060
			public const int image_Status = 2131165280;
			
			// aapt resource value: 0x7f070034
			public const int iv_Photo = 2131165236;
			
			// aapt resource value: 0x7f07003a
			public const int latLabel = 2131165242;
			
			// aapt resource value: 0x7f070039
			public const int latSection = 2131165241;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout1 = 2131165187;
			
			// aapt resource value: 0x7f07002c
			public const int linearLayout10 = 2131165228;
			
			// aapt resource value: 0x7f070031
			public const int linearLayout11 = 2131165233;
			
			// aapt resource value: 0x7f070036
			public const int linearLayout12 = 2131165238;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout2 = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout3 = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout4 = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout5 = 2131165201;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout6 = 2131165207;
			
			// aapt resource value: 0x7f07001b
			public const int linearLayout7 = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int linearLayout8 = 2131165214;
			
			// aapt resource value: 0x7f070026
			public const int linearLayout9 = 2131165222;
			
			// aapt resource value: 0x7f070083
			public const int list_Milestone = 2131165315;
			
			// aapt resource value: 0x7f07004c
			public const int longSection = 2131165260;
			
			// aapt resource value: 0x7f07005e
			public const int menu_ChangeServer = 2131165278;
			
			// aapt resource value: 0x7f07005d
			public const int menu_Document = 2131165277;
			
			// aapt resource value: 0x7f07005b
			public const int menu_Issues = 2131165275;
			
			// aapt resource value: 0x7f07005c
			public const int menu_Milestone = 2131165276;
			
			// aapt resource value: 0x7f070056
			public const int menu_Project = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int menu_Task = 2131165271;
			
			// aapt resource value: 0x7f07005a
			public const int menu_Ticket = 2131165274;
			
			// aapt resource value: 0x7f0700a1
			public const int menu_help = 2131165345;
			
			// aapt resource value: 0x7f0700a3
			public const int menu_reset = 2131165347;
			
			// aapt resource value: 0x7f0700a0
			public const int menu_search = 2131165344;
			
			// aapt resource value: 0x7f0700a2
			public const int menu_server = 2131165346;
			
			// aapt resource value: 0x7f070050
			public const int progressBar1 = 2131165264;
			
			// aapt resource value: 0x7f07003f
			public const int relativeLayout1 = 2131165247;
			
			// aapt resource value: 0x7f070047
			public const int relativeLayout2 = 2131165255;
			
			// aapt resource value: 0x7f07004a
			public const int relativeLayout3 = 2131165258;
			
			// aapt resource value: 0x7f070069
			public const int scrollView1 = 2131165289;
			
			// aapt resource value: 0x7f070019
			public const int sp_AssignedTo = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int sp_Owner = 2131165212;
			
			// aapt resource value: 0x7f070015
			public const int sp_Priority = 2131165205;
			
			// aapt resource value: 0x7f07000f
			public const int sp_Project = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int sp_Status = 2131165203;
			
			// aapt resource value: 0x7f070049
			public const int tabcontent = 2131165257;
			
			// aapt resource value: 0x7f070040
			public const int tableLayout1 = 2131165248;
			
			// aapt resource value: 0x7f070061
			public const int tableLayout2 = 2131165281;
			
			// aapt resource value: 0x7f070072
			public const int tableLayout3 = 2131165298;
			
			// aapt resource value: 0x7f070078
			public const int tableLayout4 = 2131165304;
			
			// aapt resource value: 0x7f070080
			public const int tableLayout5 = 2131165312;
			
			// aapt resource value: 0x7f070008
			public const int tableRow1 = 2131165192;
			
			// aapt resource value: 0x7f07007c
			public const int tableRow10 = 2131165308;
			
			// aapt resource value: 0x7f07002b
			public const int tableRow11 = 2131165227;
			
			// aapt resource value: 0x7f070030
			public const int tableRow12 = 2131165232;
			
			// aapt resource value: 0x7f070035
			public const int tableRow13 = 2131165237;
			
			// aapt resource value: 0x7f07000c
			public const int tableRow2 = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int tableRow3 = 2131165200;
			
			// aapt resource value: 0x7f070016
			public const int tableRow4 = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int tableRow5 = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int tableRow6 = 2131165213;
			
			// aapt resource value: 0x7f070025
			public const int tableRow7 = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int tableRow8 = 2131165223;
			
			// aapt resource value: 0x7f070029
			public const int tableRow9 = 2131165225;
			
			// aapt resource value: 0x7f070048
			public const int tabs = 2131165256;
			
			// aapt resource value: 0x7f070091
			public const int text = 2131165329;
			
			// aapt resource value: 0x7f070055
			public const int textView1 = 2131165269;
			
			// aapt resource value: 0x7f070064
			public const int textView10 = 2131165284;
			
			// aapt resource value: 0x7f07000a
			public const int textView11 = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int textView12 = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int textView13 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int textView14 = 2131165204;
			
			// aapt resource value: 0x7f070018
			public const int textView15 = 2131165208;
			
			// aapt resource value: 0x7f07001f
			public const int textView16 = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int textView17 = 2131165218;
			
			// aapt resource value: 0x7f070028
			public const int textView18 = 2131165224;
			
			// aapt resource value: 0x7f070032
			public const int textView19 = 2131165234;
			
			// aapt resource value: 0x7f070005
			public const int textView2 = 2131165189;
			
			// aapt resource value: 0x7f070087
			public const int textView21 = 2131165319;
			
			// aapt resource value: 0x7f07006e
			public const int textView23 = 2131165294;
			
			// aapt resource value: 0x7f07006f
			public const int textView24 = 2131165295;
			
			// aapt resource value: 0x7f070070
			public const int textView25 = 2131165296;
			
			// aapt resource value: 0x7f070073
			public const int textView26 = 2131165299;
			
			// aapt resource value: 0x7f070074
			public const int textView27 = 2131165300;
			
			// aapt resource value: 0x7f070079
			public const int textView28 = 2131165305;
			
			// aapt resource value: 0x7f07007a
			public const int textView29 = 2131165306;
			
			// aapt resource value: 0x7f070058
			public const int textView3 = 2131165272;
			
			// aapt resource value: 0x7f07007b
			public const int textView30 = 2131165307;
			
			// aapt resource value: 0x7f07008b
			public const int textView40 = 2131165323;
			
			// aapt resource value: 0x7f07008c
			public const int textView41 = 2131165324;
			
			// aapt resource value: 0x7f07008d
			public const int textView42 = 2131165325;
			
			// aapt resource value: 0x7f07008e
			public const int textView43 = 2131165326;
			
			// aapt resource value: 0x7f07009c
			public const int textView44 = 2131165340;
			
			// aapt resource value: 0x7f07009a
			public const int textView46 = 2131165338;
			
			// aapt resource value: 0x7f07009d
			public const int textView48 = 2131165341;
			
			// aapt resource value: 0x7f070077
			public const int tv_ActualEndDate = 2131165303;
			
			// aapt resource value: 0x7f07008f
			public const int tv_ActualHours = 2131165327;
			
			// aapt resource value: 0x7f070076
			public const int tv_ActualStartDate = 2131165302;
			
			// aapt resource value: 0x7f07006d
			public const int tv_AlloHours = 2131165293;
			
			// aapt resource value: 0x7f070090
			public const int tv_AllocatedHours = 2131165328;
			
			// aapt resource value: 0x7f07009e
			public const int tv_AssignTo = 2131165342;
			
			// aapt resource value: 0x7f070075
			public const int tv_Client = 2131165301;
			
			// aapt resource value: 0x7f070085
			public const int tv_ClientName = 2131165317;
			
			// aapt resource value: 0x7f07006b
			public const int tv_Code = 2131165291;
			
			// aapt resource value: 0x7f070062
			public const int tv_CreatedPerson = 2131165282;
			
			// aapt resource value: 0x7f07007d
			public const int tv_DeliveryManager = 2131165309;
			
			// aapt resource value: 0x7f070071
			public const int tv_Department = 2131165297;
			
			// aapt resource value: 0x7f07008a
			public const int tv_DepartmentName = 2131165322;
			
			// aapt resource value: 0x7f070082
			public const int tv_Description = 2131165314;
			
			// aapt resource value: 0x7f070023
			public const int tv_EndDate = 2131165219;
			
			// aapt resource value: 0x7f07005f
			public const int tv_MilestoneName = 2131165279;
			
			// aapt resource value: 0x7f070081
			public const int tv_Notes = 2131165313;
			
			// aapt resource value: 0x7f070089
			public const int tv_OpenIssues = 2131165321;
			
			// aapt resource value: 0x7f070088
			public const int tv_OpenTasks = 2131165320;
			
			// aapt resource value: 0x7f070086
			public const int tv_OpenTickets = 2131165318;
			
			// aapt resource value: 0x7f07009f
			public const int tv_Owner = 2131165343;
			
			// aapt resource value: 0x7f07007f
			public const int tv_ProjectCoordinator = 2131165311;
			
			// aapt resource value: 0x7f07007e
			public const int tv_ProjectManager = 2131165310;
			
			// aapt resource value: 0x7f070084
			public const int tv_ProjectName = 2131165316;
			
			// aapt resource value: 0x7f07006c
			public const int tv_RefCode = 2131165292;
			
			// aapt resource value: 0x7f070020
			public const int tv_StartDate = 2131165216;
			
			// aapt resource value: 0x7f07009b
			public const int tv_Status = 2131165339;
			
			// aapt resource value: 0x7f070099
			public const int tv_TaskName = 2131165337;
			
			// aapt resource value: 0x7f07004d
			public const int tv_password = 2131165261;
			
			// aapt resource value: 0x7f070068
			public const int tv_projectname = 2131165288;
			
			// aapt resource value: 0x7f07004b
			public const int tv_username = 2131165259;
			
			// aapt resource value: 0x7f070001
			public const int view1 = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int view2 = 2131165190;
			
			// aapt resource value: 0x7f070059
			public const int view3 = 2131165273;
			
			// aapt resource value: 0x7f070065
			public const int webView1 = 2131165285;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddTask = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CheckInstance = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditTask = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Home = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainContentLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MenuLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MilestoneList = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int OpenTaskView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Project = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ProjectDetailLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ProjectList = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SpinnerItemDropdown = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SpinnerItemText = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int StatusRow = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Task = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int TaskList = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int TaskListView = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu_home = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu_login = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
